### ISSUE TITLE
Make ready for release

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/savvyr#19]
To do:

- [x] README
- [x] NEWS
- [x] use sticker
- [x] pkgdown page
- [x] package description
- [x] confirm maintainer
- [x] remove `Remotes`

**Comment by danielinteractive** [comment]
Hi @dgkf , one question - in the description file we currently have `Remotes` for `openpharma/roxytypes` and `openpharma/roxylint`. We cannot keep this for CRAN submission.
Any chance you could release those to CRAN? If not, what would be another solution?

**Comment by dgkf** [comment]
I think you could safely remove them from both `suggests` and `Remotes` since they are only used for generating documentation. 

For example, [`dplyr`'s DESCRIPTION](https://github.com/tidyverse/dplyr/blob/main/DESCRIPTION) doesn't even mention `roxygen2`

Including it in `suggests` and `Remotes` is really just a helpful construct for ensuring developers will also have these packages when building docs. 

I'm seeing a growing trend toward using [`Config/Needs/<purpose>`](https://pak.r-lib.org/reference/package-dependency-types.html?q=Config/#extra-dependencies) for these types of developer dependencies, so instead you could do something like:

```
Config/Needs/documentation:
  roxytypes=github::openpharma/roxytypes
  roxylint=github::openpharma/roxylint
```

`remotes` won't pick up these dependencies, but I think `pak` will.

**Comment by dgkf** [comment]
That said, I think it might be time for us to also pursue publishing these to CRAN. Have you had any further issues with them that should be resolved before a first published release?

**Comment by danielinteractive** [comment]
Cool thanks Doug - honestly I think especially roxytypes is ready for CRAN. I haven't really used roxylint actively I think

**Comment by danielinteractive** [comment]
@cicdguy do you think it would be easy to add the `pak::pkg_install(..., dependencies = c("all", "Config/Needs/documentation"))` to the workflow somewhere [here](https://github.com/openpharma/savvyr/blob/main/.github/workflows/check.yaml#L44) or not? Just to understand if that would be a suitable option for the short term.

**Comment by danielinteractive** [comment]
Thanks @cicdguy for the assessment, that is helpful to know. Then it won't be a short term solution for this package release. 
I leave it to you and @dgkf to further develop that idea.
@dgkf where do we stand with the `roxylint` and `roxytypes` to CRAN submissions?

**Comment by dgkf** [comment]
> > @cicdguy do you think it would be easy to add the `pak::pkg_install(..., dependencies = c("all", "Config/Needs/documentation"))` to the workflow somewhere [here](https://github.com/openpharma/savvyr/blob/main/.github/workflows/check.yaml#L44) or not? Just to understand if that would be a suitable option for the short term.
> 
> We'll need to refactor the workflows, can't add it directly in there. Should be possible though. We can track it as a separate effort but delivery won't be anytime soon.

Wherever you install the package, you can use `pkg::local_install()` and it will automatically pick up _all_ `Config/Needs/*` dependencies. Some tools are starting to recommend some standard categories (I think `website` seems to be the convention for docs pages), but I'd probably just let the dust settle a bit on this trend before trying to be too selective - I would just pull all developer dependencies and be done with it.

**Comment by danielinteractive** [comment]
So just to be sure: we can or cannot just put some additional line `pak::local_install()` into the current workflow file somewhere? Just double checking because my GHA as well as pak skills are too low to answer this question :)

**Comment by walkowif** [comment]
Adding to what @cicdguy said, installation via `pak` is technically possible, but would need to happen separately for each of the workflows (in which the installation via `pak` should happen) 'imported' with the `uses` keyword  [here](https://github.com/openpharma/savvyr/blob/main/.github/workflows/check.yaml).

So adding this as a modification to `.github/workflows/check.yaml` file itself is not possible, this needs to happen in `r.pkg.template`.

We'd also have to assess how this change interacts with other ways dependencies are installed in the workflows, e.g. staged.dependencies.

**Comment by danielinteractive** [comment]
Thanks @cicdguy , @dgkf and @walkowif for your help!
